# From: http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/
build: false

environment:
  matrix:
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON_VERSION% %PYTHON% %PYTHON_ARCH%"

install:
  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build psutil
  - conda update -q conda
  - conda info -a
  - conda install requests
  - python -c "import requests; env=requests.get('https://raw.githubusercontent.com/darribas/gds_env/master/gds_py/gds_py.yml').text; fo=open('env.yml', 'w'); fo.write(env); fo.close();print('env.yml downloaded successfully');"
  - conda-env create -f env.yml
  - cmd: call %PYTHON%\Scripts\activate.bat
  - conda activate gds
  - pip install -r https://github.com/darribas/gds_env/raw/master/gds_py/gds_py_pip.txt

test_script:
  - jupyter nbconvert --to markdown --execute --stdout --ExecutePreprocessor.timeout=600 content/b*/*.ipynb 
