# Environment file to build website on each commit
name: book
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7.*
  - sphinx=2.4.4
  - pip
  - pyppeteer
  - pip:
      - jupyter-book==0.7.3
