name: Test GDS Course

on:
  push:
    branches: [ master ]

jobs:

  Test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        env:
          - https://github.com/darribas/gds_env/raw/master/gds_py/gds_py.yml
        include:
          - env: https://github.com/darribas/gds_env/raw/master/gds_py/gds_py.yml
            os: macos-latest
          - env: https://github.com/darribas/gds_env/raw/master/gds_py/gds_py.yml
            os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: s-weigand/setup-conda@v1.0.4
        with:
          activate-conda: false

      - name: Install GDS Env
        shell: bash
        run: |
          wget https://raw.githubusercontent.com/darribas/gds_env/master/gds_py/gds_py.yml -O env.yml
          conda env create -f env.yml
          source activate gds
          pip install -r https://github.com/darribas/gds_env/raw/master/gds_py/gds_py_pip.txt

      - name: Check and Log Environment
        shell: bash
        run: |
          source activate gds
          conda info
          # Print conda list
          conda list
          
      - name: Test Blocks
        shell: bash
        continue-on-error: false
        run: |
          source activate gds
          make test
